repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://gitlab.com/iamlikeme/nbhooks
    rev: 1.0.0
    hooks:
      - id: nb-ensure-clean
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff-format
        args: [ --preview ]
      - id: ruff
        args: [ --preview, --fix,--unsafe-fixes ]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.4
    hooks:
      - id: uv-lock
