name: PR tests
on:
  pull_request:
    paths:
        - 'tabular_orchestrated/**'
        - 'tests/**'
        - '.github/workflows/ci.yml'
        - 'pyproject.toml'
        - 'uv.lock'
  workflow_dispatch:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - run: pipx install uv
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: uv
      - name: Install OS Dependencies
        if: matrix.os == 'macos-latest'
        run: brew install libomp

#      - run: make
      - run: make test
    continue-on-error: true
