name: Code Quality

on:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: Code Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - run: uv python install 3.11
      - run: uv sync --all-extras
      - run: make check
      - run: make build-kfp
        continue-on-error: true



      - name: Check for changes
        id: check_changes
        run: |
          if ! git diff --exit-code tabular_orchestrated_kfp; then
            echo "changes=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Fail if no changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          exit 1
      - run: uv run mypy . --config-file pyproject.toml
