name: Publish Package

on:
  release:
    types: [ published ]
  pull_request:


permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install uv
      - uses: actions/setup-python@v5
#      - run: make
#      - run: make test
      - run: uv build
      - run: uv publish --token  ${{ secrets.PYPI_API_TOKEN }}
