name: Publish Package

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install uv
      - uses: actions/setup-python@v5
      - run: make
      - run: make test
      - run: uv version ${{ github.ref_name }}
      - run: uv build
      - run: uv config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      - run: uv publish
