name: tests-imports
on:
  pull_request:
    paths:
        - 'tabular_orchestrated/**'
        - 'tests/**'
        - '.github/workflows/ci.yml'
        - 'pyproject.toml'
        - 'uv.lock'
  workflow_dispatch:
jobs:

  tests-imports:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extra: [ 'mljar','spliter','deepchecks','editor']
    steps:
      - uses: actions/checkout@v4
      - name: Install OS Dependencies
        if: matrix.os == 'macos-latest'
        run: brew install libomp
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - run: uv python install 3.11
      - run: uv sync --extra ${{ matrix.extra }} --frozen
      - run: uv run pytest tests/imports_checks/test_${{ matrix.extra }}_imports.py
    continue-on-error: true
